kumuluzee:
  name: polnilnice-service
  env:
    name: dev
  version: 1.0.0
  server:
    base-url: http://localhost:8080
    http:
      port: 8080
  datasources:
    - jndi-name: jdbc/PolnilniceDS
      connection-url: jdbc:postgresql://192.168.99.100:5432/polnilnice-data
      username: dbuser
      password: postgres
  config:
    consul:
      agent: http://192.168.99.100:8500
  discovery:
    consul:
      agent: http://192.168.99.100:8500

rest-properties:
  maintenance-mode: false
